### ISSUE TITLE
This is an error about Windows

### ISSUE THREAD

**Issue by AsuraZhu** [imagemin/pngquant-bin#111]
const libpng = process.platform === 'darwin' ? 'libpng' : 'libpng-dev';

If my system was Windows, I would get a prompt about a Linux download error.

I had an error downloading from Windows, and this error bothered me.

**Comment by Nemesis-AS** [comment]
I am getting the Linux error on Windows, is there any way to fix it?

**Comment by 1000ch** [comment]
b80c567 outputs error directly, but let me close this problem even though the install script for Windows is still not prepared.
