### ISSUE TITLE
improper message

### ISSUE THREAD

**Issue by bill2004158** [imagemin/pngquant-bin#114]
https://github.com/imagemin/pngquant-bin/blob/master/lib/install.js#L25
it shows "pngquant failed to build, make sure that ${libpng} is installed"

I am trying to run command "npm install pngquant-bin" in **mac**.
actually, I already installed libpng.
and still got that error message.

and I find out, it is because cannot find **zlib** when config.
then I installed zlib using command "brew install zlib".
however, still error,

checked the config script, it seems missing "pkg-config", which cause cannot find zlib when config
then I install pkg-config, using command "pkg-config"

and finally  "npm install pngquant-bin" works properly.

so can you update that messge to show more detail about error?

**Comment by 1000ch** [comment]
Solved by b80c567.
