### ISSUE TITLE
Broken Linux binary, and failure to build from source

### ISSUE THREAD

**Issue by hillct** [imagemin/pngquant-bin#12]
The supplied Linux binary is unusable on any modern system. The error I get when trying to utilize  the supplied binary is: 
./pngquant: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./pngquant)

My tests were on an up-to-date Centos 6 box but it could be reproduced on any modern linux box where  /lib64/libc.so.6 links to an even incrementally newer release

I realize that in theory the mechanism is supposed to fall back to building from source, but if the source build doesn't follow whatever build pattern is expected, it would of course fail as it does in this case. I'm not familiar enough with bin-wrapper to say whether or not the build pattern can be specified with sufficient flexibility to get it to work, but that's where I'd look for a fix to this issue.

**Comment by magic890** [comment]
Same error today on CentOS 6:
    /node_modules/imagemin-pngquant/node_modules/pngquant-bin/vendor/pngquant: /lib64/libc.so.6: version `GLIBC_2.14' not found.
