### ISSUE TITLE
Error on MacOS pngquant-bin/vendor/pngquant ENOENT

### ISSUE THREAD

**Issue by llamerr** [imagemin/pngquant-bin#120]
Getting error upon running `gatsby develop`. No error happened when I did `npm install`

```
WorkerError: Processing /Users/alexey/proj/gatsby/src/images/shared/glasses-image.png failed
  Original error:
  Command failed with ENOENT: /Users/alexey/proj/gatsby/node_modules/pngquant-bin/vendor/pngquant - --strip --quality 50-75
  spawn /Users/alexey/proj/gatsby/node_modules/pngquant-bin/vendor/pngquant ENOENT
```

MacOS: 11.2.3 (20D91)
npm: 7.6.2
node: v14.15.3

All I have inside `vendor` folder is `source` folder with `pngquant.tar.gz` inside it

**Comment by llamerr** [comment]
Seems like postinstall not being executed. Once I tried same command in empty folder/repo, it did all properly

**Comment by ankurparihar** [comment]
exactly the same error I'm also getting, were you able to find the root cause @llamerr ?

**Comment by llamerr** [comment]
> exactly the same thing with me using npm 6.14.5, were you able to find the root cause @llamerr ?

I don't think so, existing solution (do from scratch) probably was good enough for me.

**Comment by ankurparihar** [comment]
I saw this happening on a freshly cloned project as well, had to add `"postinstall": "node node_modules/pngquant-bin/lib/install"` in my project's package.json to get around this.

It seems more like a problem coming from npm. Seems and interesting bug, I'll try to look further into this.
