### ISSUE TITLE
error while loading shared libraries: libimagequant.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by rivonia** [imagemin/pngquant-bin#130]
Am getting the following error when running `npm install` with the latest version of pngquant-bin:

	npm ERR! code 1
	npm ERR! path /root/workspace/myspace/node_modules/pngquant-bin
	npm ERR! command failed
	npm ERR! command sh -c node lib/install.js
	npm ERR! compiling from source
	npm ERR! Command failed: /root/workspace/myspace/node_modules/pngquant-bin/vendor/pngquant --version
	npm ERR! /root/workspace/myspace/node_modules/pngquant-bin/vendor/pngquant: error while loading shared libraries: libimagequant.so.0: cannot open shared object file: No such file or directory
	npm ERR! 
	npm ERR! 
	npm ERR! pngquant pre-build test failed
	npm ERR! Error: pngquant failed to build, make sure that libpng-dev is installed
	npm ERR!     at /root/workspace/myspace/node_modules/bin-build/node_modules/execa/index.js:231:11
	npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
	npm ERR!     at async Promise.all (index 0)

And yes, I have installed `libpng-dev`.

**Comment by 1000ch** [comment]
Please make sure to install `libimagequant` as well.

```sh
# via Homebrew for macOS
$ brew install libimagequant

# via apt-get for Debian distributions
$ apt-get install libimagequant-dev
```

**Comment by rivonia** [comment]
Yep, thanks, that seems to do the trick!

**Comment by pashster** [comment]
I got the same problem. When I run the command `sudo apt-get install libimagequant-dev` it says: `E: Unable to locate package libimagequant-dev`

OS:
```
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
```
node:
```
v16.13.2
```

npm:
```
8.1.2
```
