### ISSUE TITLE
Error detecting if "libpng-dev" is installed on Debian Wheezy

### ISSUE THREAD

**Issue by norrs** [imagemin/pngquant-bin#26]
dpkg -l | grep libpng-dev   shows nothing, while running yo angular from yo's tutorial where one of the dependencies is pngquant-bin I get the following:

> pngquant-bin@0.3.1 postinstall /home/rockj/dev/javascript/experiments/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin
> node index.js

✗ pre-build test failed, compiling from source...
libpng-dev is installed

{ [Error: Command failed: In file included from pngquant.c:59:0:
rwpng.h:35:57: fatal error: png.h: No such file or directory
compilation terminated.
make: **\* [pngquant.o] Error 1
] killed: false, code: 2, signal: null }

> optipng-bin@0.3.8 postinstall /home/rockj/dev/javascript/experiments/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
> node index.js

...

Installing libpng12-dev on my Debian Wheezy seem to fix the issue. 

rockj@pandora:~/zedge/frontend-experiments$ dpkg -l | grep libpng-dev
rockj@pandora:~/zedge/frontend-experiments$ apt-cache show libpng-dev
N: Can't select versions from package 'libpng-dev' as it is purely virtual
N: No packages found
rockj@pandora:~/zedge/frontend-experiments$ apt-cache show libpng12-dev
Package: libpng12-dev
Source: libpng
Version: 1.2.49-1
Installed-Size: 588
Maintainer: Anibal Monsalve Salazar anibal@debian.org
Architecture: amd64
Replaces: libpng12-0-dev, libpng3-dev (<= 1.2.5)
Provides: libpng-dev, libpng12-0-dev, libpng3-dev
Depends: libpng12-0 (= 1.2.49-1), zlib1g-dev
Conflicts: libpng-dev, libpng12-0-dev, libpng2 (<< 1.0.12-3), libpng2-dev
Description-en: PNG library - development
 libpng is a library implementing an interface for reading and writing
 PNG (Portable Network Graphics) format files.
 .
 This package contains the header and development files needed to build
 programs and packages using libpng.
Homepage: http://libpng.org/pub/png/libpng.html
Description-md5: 748198d86eeddc4aa1418e7d1311203c
Tag: devel::lang:c, devel::library, implemented-in::c, role::devel-lib,
 works-with::image, works-with::image:raster
Section: libdevel
Priority: optional
Filename: pool/main/libp/libpng/libpng12-dev_1.2.49-1_amd64.deb
Size: 266282
MD5sum: 67e5fe32ccad94a449bc8a871b2d73fd
SHA1: 39e7896205d7b659921e7c1c2229da13cc319967
SHA256: c8447b3606047630a16f45da23154532949feafaa5685045204e9380f645407a

rockj@pandora:~/zedge/frontend-experiments$ apt-cache policy libpng12-dev
libpng12-dev:
  Installed: 1.2.49-1
  Candidate: 1.2.49-1
  Version table:
 **\* 1.2.49-1 0
        500 http://ftp.no.debian.org/debian/ wheezy/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by gbryant200** [comment]
grep-status -FProvides,Package -sPackage,Provides,Status libpng-dev
Package: libpng12-dev
Provides: libpng-dev, libpng12-0-dev, libpng3-dev
Status: install ok installed

Still get:
pngquant pre-build test passed successfully
pngquant failed to build, make sure that libpng-dev is installed

pngquant-bin@4.0.0
node.js version v9.9.0
npm version 5.6.0
Ubuntu 16.04

any ideas?

**Comment by candidosouza** [comment]
No meu caso no Ubuntu 18, resolvi dessa forma.

sudo apt install libpng-dev
