### ISSUE TITLE
Use `--skip-if-larger` option

### ISSUE THREAD

**Issue by sindresorhus** [imagemin/pngquant-bin#29]
https://github.com/pornel/pngquant/commit/21a9d9eb01dd0b7a559f51b422f7f2c9d5ba8912#diff-04c6e90faac2675aa89e2176d2eec7d8R60

No need to expose it. We just set it to true. I don't see any reason anyone would want it to be false.

**Comment by ryanpcmcquen** [comment]
@kevva, is this still active, because I am not seeing it in the current code ...
