### ISSUE TITLE
Don't support node_modules as symbolic link

### ISSUE THREAD

**Issue by nervo** [imagemin/pngquant-bin#34]
This one was hard to find :)
We had some several issues when deploying our applications via capistrano, and found only today the origin.

Easy to reproduce:

    $ mkdir test
    $ ln -s test node_modules
    $ npm install pngquant-bin

Now, admire your process list, full of respawned

    test/pngquant-bin/vendor/pngquant --version

Watch your memory growing, watch your swap growing, and cry...

Btw, it seems that this package is not the only one to have this bug, and i suspect a sub dependency, or a behavior shared between other packages.

But, hey, we need to start somewhere :)

**Comment by benji07** [comment]
:+1:

**Comment by kevva** [comment]
This is fixed in bin-wrapper. Just haven't bumped it on the bin-wrapper modules yet.

**Comment by nervo** [comment]
(I don't want to give you any advices, but a regression test on this could be a great idea :))
