### ISSUE TITLE
Compilation from source fail on alpine linux

### ISSUE THREAD

**Issue by WnP** [imagemin/pngquant-bin#36]
OS: alpine linux
kernel: Linux 3.14.36-0-grsec
npm: 2.7.3
nodejs: v0.10.33

```sh
$ npm install --save pngquant-bin
/
> pngquant-bin@2.0.3 postinstall /home/taiga/tmp/node_modules/pngquant-bin
> node lib/install.js

  ⚠ spawn ENOENT
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
    at ChildProcess.exithandler (child_process.js:648:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Socket.<anonymous> (child_process.js:969:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
pngquant-bin@2.0.3 node_modules/pngquant-bin
├── logalot@2.1.0 (figures@1.3.5, squeak@1.2.0)
├── bin-build@2.1.1 (exec-series@1.0.1, url-regex@2.1.2, tempfile@1.1.0, archive-type@2.0.0, rimraf@2.3.2, decompress@2.2.1, download@3.3.0)
└── bin-wrapper@2.1.3 (os-filter-obj@1.0.3, is-path-global@1.0.1, download-status@2.1.1, npm-installed@1.0.0, bin-check@1.0.0, bin-version-check@2.1.0, globby@1.2.0, lnfs@1.0.0, download@3.3.0)
```
indeed I've installed `libpng-dev`, does a specific version is required?

I have `libpng-dev-1.6.16` installed

**Comment by WnP** [comment]
fixed, just need to install `bash` … maybe the error message should mention that

**Comment by kevva** [comment]
@WnP, it's kinda impossible to cover all use cases between Linux distros etc.

**Comment by WnP** [comment]
@kevva yes I gess too ;)

thanks

**Comment by kevva** [comment]
Happy it's working now :).

**Comment by osule** [comment]
Image loader depends on pngquant binary.

When pngquant-bin npm module is installed it compiles pngquant binary using g++, zlib-dev and libpng-dev.

It is unfortunate that the error messages are not clear enough and you're only graced with an unhelpful one.

Make sure to run the following before npm install or yarn install _if using an alpine base image_.

```bash
apk --no-cache update \ 
&& apk --no-cache add g++ zlib-dev libpng-dev \
&&  rm -fr /var/cache/apk/*
You may replace installing g++ zlib-dev with build-base instead.
```
https://stackoverflow.com/a/49857106/5189811

**Comment by hanxi** [comment]
https://github.com/maxmind/libmaxminddb/issues/9#issuecomment-30836272
