### ISSUE TITLE
Upgrade to 2.4.0

### ISSUE THREAD

**Issue by sindresorhus** [imagemin/pngquant-bin#37]
https://raw.githubusercontent.com/pornel/pngquant/master/CHANGELOG
- [ ] Linux x86
- [x] Linux x64 (https://github.com/imagemin/pngquant-bin/commit/09551b715e89bb395e7a7a61d85174403bf80144)
- [x] OS X (https://github.com/imagemin/pngquant-bin/commit/1a2e7fbf3c211620871cc7010b58fbbb7d1688e1)
- [x] Windows (https://github.com/imagemin/pngquant-bin/commit/04ac5a935101c5d8e537d03707b95d732029948a)

**Comment by kevva** [comment]
@sindresorhus, could you compile a OS X binary?

**Comment by sindresorhus** [comment]
OS X and Windows are already precompiled by upstream: https://pngquant.org/

**Comment by kevva** [comment]
Woot, nice.

**Comment by shinnn** [comment]
v2.5.0 has been released.

**Comment by kevva** [comment]
I'll build some Linux ones.

**Comment by vitalymak** [comment]
v2.5.0 has been released. https://github.com/pornel/pngquant/tree/2.5.2

**Comment by CraigBeswetherick** [comment]
version 2.5.2 is now out - can this be updated please? I had to manually replace the file to remove artefacts created by an out of date pngquant library in my current project.

**Comment by thasmo** [comment]
@sindresorhus, got time to update this to [pngquant 2.6](https://raw.githubusercontent.com/pornel/pngquant/master/CHANGELOG)? Thanks!

**Comment by jason-c-child** [comment]
any plans to build against libpng v1.6.x?

**Comment by strarsis** [comment]
v2.8.0 has been released. https://github.com/pornel/pngquant/releases/tag/2.8.0

**Comment by sindresorhus** [comment]
Closing in favor of https://github.com/imagemin/pngquant-bin/issues/60.
