### ISSUE TITLE
Why do you package modules with binaries?

### ISSUE THREAD

**Issue by dizballanze** [imagemin/pngquant-bin#38]
Hi.
Binaries from your module doesn't portable and not work on systems with different libc version.
Why do you package modules with binaries?

**Comment by sindresorhus** [comment]
We ship pre-built binaries to make it easier and faster for most people, but it also falls back to [compiling from source](https://github.com/imagemin/pngquant-bin/blob/70cbe41e7e42f0ac5d20834b1e68fd73883ebfbc/lib/install.js#L11) if the binary fails.

**Comment by kevva** [comment]
We're also going to add a fallback to already globally installed binaries if the two former steps fail.
