### ISSUE TITLE
Could pngquant download source file from another url

### ISSUE THREAD

**Issue by keelii** [imagemin/pngquant-bin#44]
I'v noticed that pngquant download source file from `raw.github.com/...`

> https://github.com/imagemin/pngquant-bin/blob/master/lib/index.js#L6

For some reason, github is blocked sometimes in some country, I think The node-sass's way maybe better:

> https://github.com/sass/node-sass#binary-configuration-parameters

**Comment by shinnn** [comment]
All countries should not block Github URL.
