### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by dvdrndlph** [imagemin/pngquant-bin#46]
I am seeing this:

npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/W17626/.nvm/versions/node/v6.2.0/bin/node" "/Users/w17626/.nvm/versions/node/v6.2.0/bin/npm" "install"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE

npm ERR! pngquant-bin@0.1.7 postinstall: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pngquant-bin@0.1.7 postinstall script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pngquant-bin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pngquant-bin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pngquant-bin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/W17626/repo/motoinsights/moto-insights/default/web/npm-debug.log

In the log, I see this:

58417 verbose stack Error: pngquant-bin@0.1.7 postinstall: `node index.js`
58417 verbose stack Exit status 1
58417 verbose stack     at EventEmitter.<anonymous> (/Users/W17626/.nvm/versions/node/v6.2.0/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
58417 verbose stack     at emitTwo (events.js:106:13)
58417 verbose stack     at EventEmitter.emit (events.js:191:7)
58417 verbose stack     at ChildProcess.<anonymous> (/Users/W17626/.nvm/versions/node/v6.2.0/lib/node_modules/npm/lib/utils/spawn.js:24:14)
58417 verbose stack     at emitTwo (events.js:106:13)
58417 verbose stack     at ChildProcess.emit (events.js:191:7)
58417 verbose stack     at maybeClose (internal/child_process.js:850:16)
58417 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
58418 verbose pkgid pngquant-bin@0.1.7
58419 verbose cwd /Users/W17626/repo/motoinsights/moto-insights/default/web
58420 error Darwin 15.4.0
58421 error argv "/Users/W17626/.nvm/versions/node/v6.2.0/bin/node" "/Users/w17626/.nvm/versions/node/v6.2.0/bin/npm" "install"
58422 error node v6.2.0
58423 error npm  v3.8.9
58424 error code ELIFECYCLE
58425 error pngquant-bin@0.1.7 postinstall: `node index.js`
58425 error Exit status 1
58426 error Failed at the pngquant-bin@0.1.7 postinstall script 'node index.js'.
58426 error Make sure you have the latest version of node.js and npm installed.
58426 error If you do, this is most likely a problem with the pngquant-bin package,
58426 error not with npm itself.
58426 error Tell the author that this fails on your system:
58426 error     node index.js
58426 error You can get information on how to open an issue for this project with:
58426 error     npm bugs pngquant-bin
58426 error Or if that isn't available, you can get their info via:
58426 error     npm owner ls pngquant-bin
58426 error There is likely additional logging output above.
58427 verbose exit [ 1, true ]

Thanks,
Dave

**Comment by dvdrndlph** [comment]
When I rerun, I see this:

web $ npm install
npm WARN deprecated find-file@0.1.4: Use the globby package instead

> pngquant-bin@0.1.7 postinstall /Users/W17626/repo/motoinsights/moto-insights/default/web/node_modules/pngquant-bin
> node index.js

path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received { name: 'pngquant',
  url: 'https://raw.github.com/sindresorhus/node-pngquant-bin/v0.1.7/vendor/osx/pngquant' }
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1355:5)
    at /Users/W17626/repo/motoinsights/moto-insights/default/web/node_modules/download/index.js:35:43
    at each (/Users/W17626/repo/motoinsights/moto-insights/default/web/node_modules/each-async/each-async.js:63:4)
    at module.exports (/Users/W17626/repo/motoinsights/moto-insights/default/web/node_modules/download/index.js:33:5)
    at BinWrapper._download (/Users/W17626/repo/motoinsights/moto-insights/default/web/node_modules/pngquant-bin/node_modules/bin-wrapper/index.js:283:14)
    at BinWrapper.check (/Users/W17626/repo/motoinsights/moto-insights/default/web/node_modules/pngquant-bin/node_modules/bin-wrapper/index.js:75:10)
    at /Users/W17626/repo/motoinsights/moto-insights/default/web/node_modules/pngquant-bin/index.js:27:5
    at FSReqWrap.cb [as oncomplete] (fs.js:251:19)
mymotoportal@0.0.0 /Users/W17626/repo/motoinsights/moto-insights/default/web
└── (empty)

npm WARN mymotoportal@0.0.0 No description
npm WARN mymotoportal@0.0.0 No repository field.
npm WARN mymotoportal@0.0.0 No license field.
npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/W17626/.nvm/versions/node/v6.2.0/bin/node" "/Users/w17626/.nvm/versions/node/v6.2.0/bin/npm" "install"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE

npm ERR! pngquant-bin@0.1.7 postinstall: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pngquant-bin@0.1.7 postinstall script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pngquant-bin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pngquant-bin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pngquant-bin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/W17626/repo/motoinsights/moto-insights/default/web/npm-debug.log
npm ERR! code 1

**Comment by shinnn** [comment]
> pngquant-bin@0.1.7

Too older version.
