### ISSUE TITLE
version in npm package

### ISSUE THREAD

**Issue by drmrbrewer** [imagemin/pngquant-bin#49]
I'm using pngquant in my node.js app on ubuntu (cloud 9 / heroku) via the npm package at https://www.npmjs.com/package/pngquant-bin.

But I note that the resulting pngquant binary is only 2.4.1 (April 2015).  Why is that, and how do I use the most recent version of pngquant (in a node.js app) on the ubuntu platform?

**Comment by shinnn** [comment]
Already discussed in https://github.com/imagemin/pngquant-bin/issues/37.
