### ISSUE TITLE
Installation failure won't stop npm install

### ISSUE THREAD

**Issue by bascht** [imagemin/pngquant-bin#50]
I'm not sure if this is a npm or a package problem, but a failing installation won't make `npm install` fail - which makes it kind of hard to debug, especially in automated build chains.

Shouldn't `npm install` just abort, if there is no prebuilt binary and none of the build deps are available? 

```javascript
{
  "private": true,
  "name": "test",
  "version": "1.0.0",
  "dependencies": {
    "pngquant-bin": "^3.1.1"
  }
}
```
``` shell
/tmp #  npm install
> pngquant-bin@3.1.1 postinstall /tmp/node_modules/pngquant-bin
> node lib/install.js

  ⚠ spawn /tmp/node_modules/pngquant-bin/vendor/pngquant ENOENT
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:486:12)
nsp@2.6.1 node_modules/nsp
├── path-is-absolute@1.0.0
├── nodesecurity-npm-utils@5.0.0
├── semver@5.1.0
├── chalk@1.1.3 (escape-string-regexp@1.0.5, ansi-styles@2.2.1, supports-color@2.0.0, has-ansi@2.0.0, strip-ansi@3.0.1)
├── cli-table@0.3.1 (colors@1.0.3)
├── wreck@6.3.0 (boom@2.10.1, hoek@2.16.3)
├── rc@1.1.6 (ini@1.3.4, deep-extend@0.4.1, strip-json-comments@1.0.4, minimist@1.2.0)
├── subcommand@2.0.3 (cliclopts@1.1.1, xtend@4.0.1, minimist@1.2.0, debug@2.2.0)
├── https-proxy-agent@1.0.0 (extend@3.0.0, debug@2.2.0, agent-base@2.0.1)
└── joi@6.10.1 (topo@1.1.0, isemail@1.2.0, hoek@2.16.3, moment@2.12.0)

pngquant-bin@3.1.1 node_modules/pngquant-bin
├── logalot@2.1.0 (figures@1.7.0, squeak@1.3.0)
├── bin-build@2.2.0 (exec-series@1.0.3, archive-type@3.2.0, url-regex@3.2.0, tempfile@1.1.1, rimraf@2.5.4, decompress@3.0.0, download@4.4.3)
└── bin-wrapper@3.0.2 (lazy-req@1.1.0, os-filter-obj@1.0.3, each-async@1.1.1, bin-check@2.0.0, bin-version-check@2.1.0, download@4.4.3)

/tmp # echo $?
0
```

**Comment by kevva** [comment]
That's intended because it's not guaranteed that the plugins will install successfully depending on what system you're using. Throwing an error would just lead to people not being able to install some modules.

I'm still hoping to improve errors in [`bin-wrapper`](http://github.com/kevva/bin-wrapper) though.

**Comment by fhemberger** [comment]
But what good is it for npm to install all other dependencies besides `pngquant-bin` correctly, if you end up with a broken application? If the binary cannot be installed or compiled from source, that's IMHO an error that should stop the installation process.

At least it would be great if `bin-wrapper` had some kind of `throwOnError` option, which let's the user decide how to handle such errors for their package.

**Comment by hashar** [comment]
The installation failing gracefully has lead to some headaches.  
Really if I depend on `pngquant-bin`, I would rather make sure `npm install` managed to install it properly. 

Can you reconsider your choice and make it fail on compilation error as one would expect?

(I have been hit by the same issue with mozjpeg@4.1.1 and jpegoptim-bin@3.0.0
