### ISSUE TITLE
Using package inside docker

### ISSUE THREAD

**Issue by schovi** [imagemin/pngquant-bin#52]
I am having webpack project which runs inside Docker container and application with node_modules is linked into container via `volumes` option.
When run application it throw following error:

```
ERROR in ./images/chat-sprite.png
Module build failed: Error: /usr/src/app/node_modules/pngquant-bin/vendor/pngquant: 1: /usr/src/app/node_modules/pngquant-bin/vendor/pngquant: �����H: not found
/usr/src/app/node_modules/pngquant-bin/vendor/pngquant: 2: /usr/src/app/node_modules/pngquant-bin/vendor/pngquant: �H__PAGEZERO�__TEXT�__text__TEXT�: not found
/usr/src/app/node_modules/pngquant-bin/vendor/pngquant: 3: /usr/src/app/node_modules/pngquant-bin/vendor/pngquant: Syntax error: "(" unexpected
```

It seems, problem has something to do with fact, that files are linked into container.
Any idea anybody? :)

**Comment by shan-du** [comment]
i got exactly the same error when running `npm start`
using `node:4.5` docker image from docker hub running `react` on `webpack`
complaining about a PNG file

**Comment by schovi** [comment]
@shan-du Found solution. You probably have installed `npm install` on you system (which is osx, or window). But Docker container runs on Debian. Problem is that this library install binary for given system which and you then run it on another. 
You have to copy `package.json` and run `npm install` inside container.

**Comment by shan-du** [comment]
Hey @schovi, thanks so much for the quick reply.
I assume running `npm install` within the container work for you right?
Running `npm install` from inside the container was what I did in fact, but no dice.
Also tried `npm install -g pngquant` to no prevail

But it's ok, I spawned the node container to replicate a production bug, but the bug is resolved since so it's all good, thanks again!

**Comment by shan-du** [comment]
EDIT: JUST got it working!
Here's what worked for me:
```bash
npm rebuild
npm uninstall
npm install
```

**Comment by shinnn** [comment]
https://github.com/imagemin/pngquant-bin/issues/52#issuecomment-260247356 is right.

**Comment by enapupe** [comment]
#52 (comment) doesn't work for me.. Do you guys know anything else about this issue? I'm running the whole build process inside the container.

**Comment by kopax** [comment]
Unfortunatly didn't work for me.

**Comment by lhew** [comment]
This worked for me as well:

```
# Dockerfile
RUN cd v0 && npm rebuild && npm uninstall && npm install &&  npm run build && cp -a build ../
```
