### ISSUE TITLE
Fail to install with: Cannot find module './src/init'

### ISSUE THREAD

**Issue by jasonm** [imagemin/pngquant-bin#53]
Hi, I'm seeing a consistent issue attempting to install `pngquant-bin`.  This has only surfaced over the last day or two AFAIK.

Here is a log of it failing on OSX with node 6.2.2/npm 3.9.5 (I recorded this b/c that combination is successful in the pngquant-bin TravisCI build): https://gist.github.com/jasonm/2fb3f65f63e49030493a60ef9ded8551  It also happens on the same OSX machine with node 0.10.41/npm 2.15.11 and node 4.4.6/npm 3.10.8.

Here is a log failing on Ubuntu 14.04 / node 0.10.38 / npm 2.14.21: https://gist.github.com/jasonm/6f39fed992e357e3960eb29ed4fdbd62

Is there any other info I could provide to help isolate/repro? Thanks!

**Comment by jguillen1984** [comment]
FWIW... Experiencing the same issue as well.

**Comment by jasonm** [comment]
I bet this is the same as imagemin/gifsicle-bin#66  and actually https://www.npmjs.com/package/gulp-sourcemaps recent release at the base of it?

**Comment by kylehood** [comment]
Also experiencing this issue using img-loader, which has pngquant-bin as a dependency.

**Comment by jasonm** [comment]
I think this is upstream https://github.com/floridoo/gulp-sourcemaps/issues/238 & best to follow there 👍

**Comment by jasonm** [comment]
Verified that adding `+    "gulp-sourcemaps": "1.7.1",` to package.json fixes

**Comment by ekryski** [comment]
@jasonm do you off hand know what is requiring gulp-sourcemaps?

**Comment by jasonm** [comment]
@ekryski here's the `npm ls` https://gist.github.com/jasonm/9188ea1f8c7c3960212c0b2b4ec16eee, appears to be `image-webpack-loader > imagemin > imagemin-{gifsicle,jpegtran,etc.} > [sometimes another subdep] > vinyl-fs > gulp-sourcemaps` but the tree is deep 👓

**Comment by ekryski** [comment]
@jasonm thanks dude. Ya I started pulling at that string and couldn't trace how deep that rabbit hole went. Regretting not shrinkwrapping my deps. Maybe we have yarn to the rescue....
