### ISSUE TITLE
Inconsist binary version across different OS

### ISSUE THREAD

**Issue by TitiHl** [imagemin/pngquant-bin#54]
Is there a plan to update Linux & Windows binary version to keep consist with MacOs?
I am using Mac for development but production environment is Ubuntu, the version difference (using different libpng) gives me different compressed result.

Thanks,
Alex

**Comment by dusterio** [comment]
I'm experiencing the same problem. I'm using CircleCI for CI and it downloads an older version of binary that fails to execute (Please recompile pngquant with the current version of libpng) thus breaking the whole build

**Comment by leachiM2k** [comment]
I have the same problem. What should be done to update e.g. Linux version?

**Comment by dusterio** [comment]
This is my workaround:
Install modern version of pngquant: apt-get install -y pngquant

Then override prehistoric version from node_modules:
rm -f ./node_modules/pngquant-bin/vendor/pngquant
ln -s `which pngquant` ./node_modules/pngquant-bin/vendor/pngquant

**Comment by shinnn** [comment]
Already discussed in https://github.com/imagemin/pngquant-bin/issues/37.
