### ISSUE TITLE
Add PATH variable to download binary from different URL

### ISSUE THREAD

**Issue by pd4d10** [imagemin/pngquant-bin#63]
Like `PHANTOMJS_CDNURL` for PhantomJS, see

https://github.com/Medium/phantomjs#deciding-where-to-get-phantomjs

Is it possible to accept a PR to add this feature?

**Comment by sindresorhus** [comment]
Can you open an issue on https://github.com/imagemin/imagemin instead? We need a solution for all plugins, not just for this one.
