### ISSUE TITLE
Fall back to binary in system path if compilation fails

### ISSUE THREAD

**Issue by jpap** [imagemin/pngquant-bin#66]
I ran into the issue discussed in #38 today:

* I'm using `imagemin` via `image-webpack-loader` on Alpine Linux (a Docker container).
* I have `cjpeg` (MozJPEG), `pngquant`, etc., installed as binaries in the path. 
* The binaries you ship don't work under Alpine because of lib dependency version mismatches; the compiler is not installed either.
* Webpack fails with `ENOENT` errors because the binaries you ship won't execute. (And an otherwise very cryptic error message.)

@kevva, it would be great if this project, as all the other `imagemin/*-bin` projects, implement the fallback to the system-installed binary as you outlined in #38.

My workaround is to delete the installed `vendor/X` binary in `node_modules` and symlink it to the system binary: it's an awful hack inserted into my CI runner build scripts that I'd prefer to avoid.

**Comment by kevva** [comment]
https://github.com/kevva/bin-wrapper/issues/50

I'm still tinkering with the `bin-wrapper` module and won't patch it until I've rewritten it.
