### ISSUE TITLE
‘postinstall’ Use a proxy

### ISSUE THREAD

**Issue by yoyo837** [imagemin/pngquant-bin#68]
For some reason, I can not use the github download link, can I support the use of a proxy address to download it？

**Comment by shinnn** [comment]
This library uses [get-proxy](https://github.com/kevva/get-proxy) to get proxy settings form environment variables.

1. Set a correct environment variable to enable proxy tunneling.
2. If 1. doesn't work, open a new issue on https://github.com/kevva/get-proxy/issues.
