### ISSUE TITLE
Install should fail if the binary doesn't work

### ISSUE THREAD

**Issue by evanj** [imagemin/pngquant-bin#72]
`lib/install.js` catches any install/compilation error and logs the message, but doesn't actually fail the install. It probably needs to re-raise the exception, so that `yarn install` or `npm install` fail if the system is configured incorrectly.

**Comment by sindresorhus** [comment]
👍

**Comment by evanj** [comment]
Should be fixed be #75. I needed this to test my statically linked libraries.

**Comment by sevaru** [comment]
@evanj Is there any progress on PR merge?
Our build system in docker can't properly cache layers due to fact that npm i is not properly exits on fails.

**Comment by evanj** [comment]
I have not heard from the project maintainers on this PR since January. I can't do much about it I'm afraid. I don't actually use this enough to feel comfortable attempting to publish a fork, so I'm afraid my only suggestion would be to create your own fork with that PR merged, and use that. Good luck!

**Comment by sevaru** [comment]
@evanj Thank you.

@sindresorhus Sorry, but is there any chance we could merge PR or have any feedback on it?
