### ISSUE TITLE
pngquant pre-build test failed on centos 6.5 glibc-2.12

### ISSUE THREAD

**Issue by a526672351** [imagemin/pngquant-bin#77]
[fsevents@^1.0.0] optional install error: Package require os(darwin) not compatible with your platform(linux)
   ✔ jpegtran pre-build test passed successfully
   ⚠ The `/www/jenkins/workspace/international-station-admin__nodejs/node_modules/_pngquant-bin@3.1.1@pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly
   ⚠ pngquant pre-build test failed
   ℹ compiling from source
   ✔ pngquant built successfully
   ✔ optipng pre-build test passed successfully

**Comment by a526672351** [comment]
![image](https://user-images.githubusercontent.com/5345266/36962116-38cc5cd8-2089-11e8-9de3-56204fcfbd94.png)
Install the binary file is wrong?

**Comment by geils** [comment]
In my case, CentOS 7.4.1708

`~$ sudo yum install libpng libpng-devel libpng12 libpng12-devel`

And it worked after that.

**Comment by bugZhang** [comment]
@geils thanks,i have the same CentOS.i have installed libpng-devel first,but it didn't work.After installed libpng12-devel, it's ok.

**Comment by zhangyuheng** [comment]
@a526672351 

Install dependence

```bash
$ yum install libpng-devel # for pngquant-bin
```

and **reinstall** `pngquant-bin`

```bash
$ node node_modules/imagemin-pngquant/node_modules/pngquant-bin/lib/install.js
```

**Comment by MWalid** [comment]
On centos 7 Installation with yarn fails, with npm works

**Comment by 1000ch** [comment]
Please make sure to install prerequisites before installing this package like https://github.com/imagemin/pngquant-bin/issues/77#issuecomment-381022874.
