### ISSUE TITLE
pngquant-bin@5.0.1 postinstall: `node lib/install.js`

### ISSUE THREAD

**Issue by hamza-iqbal** [imagemin/pngquant-bin#97]
window: 10,
node version: 10:15:0

I am cloning the project from git in windows machine.
I am getting error while run this commond npm install

I tried alot but failed,please help me.

Command failed: \node_modules\pngquant-bin\vendor\pngquant.exe --version

  ‼ pngquant pre-build test failed
  i compiling from source
  × Error: pngquant failed to build, make sure that libpng-dev is installed
    at Promise.all.then.arr (E:\New folder\node_modules\execa\index.js:231:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm WARN EVVA@1.0.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pngquant-bin@5.0.1 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pngquant-bin@5.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by zsjun** [comment]
install libpng-dev

**Comment by brunosoune** [comment]
Any solution? I have the same scenario and error.

**Comment by Allen-Wei** [comment]
> install libpng-dev

I has tried `sudo apt-get install libpng-dev`: 
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libpng-dev is already the newest version (1.6.34-1).
The following packages were automatically installed and are no longer required:
  gconf-service gconf-service-backend gconf2-common libgconf-2-4
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

then execute `sudo npm -g install pngquant-bin`:
```
/usr/local/lib/node-v10.15.1-linux-x64/bin/pngquant -> /usr/local/lib/node-v10.15.1-linux-x64/lib/node_modules/pngquant-bin/cli.js

> pngquant-bin@5.0.1 postinstall /usr/local/lib/node-v10.15.1-linux-x64/lib/node_modules/pngquant-bin
> node lib/install.js

  ⚠ EACCES: permission denied, open '/usr/local/lib/node-v10.15.1-linux-x64/lib/node_modules/pngquant-bin/vendor/pngquant'
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pngquant-bin@5.0.1 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pngquant-bin@5.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alan/.npm/_logs/2019-02-13T04_42_23_142Z-debug.log
```
the log content latest lines are: 
```
6078 info lifecycle decompress-unzip@4.0.1~postinstall: decompress-unzip@4.0.1
6079 silly postinstall decompress@4.2.0
6080 info lifecycle decompress@4.2.0~postinstall: decompress@4.2.0
6081 silly postinstall download@7.1.0
6082 info lifecycle download@7.1.0~postinstall: download@7.1.0
6083 silly postinstall download@6.2.5
6084 info lifecycle download@6.2.5~postinstall: download@6.2.5
6085 silly postinstall bin-build@3.0.0
6086 info lifecycle bin-build@3.0.0~postinstall: bin-build@3.0.0
6087 silly postinstall bin-wrapper@4.1.0
6088 info lifecycle bin-wrapper@4.1.0~postinstall: bin-wrapper@4.1.0
6089 silly postinstall execa@0.10.0
6090 info lifecycle execa@0.10.0~postinstall: execa@0.10.0
6091 silly postinstall logalot@2.1.0
6092 info lifecycle logalot@2.1.0~postinstall: logalot@2.1.0
6093 silly postinstall pngquant-bin@5.0.1
6094 info lifecycle pngquant-bin@5.0.1~postinstall: pngquant-bin@5.0.1
6095 verbose lifecycle pngquant-bin@5.0.1~postinstall: unsafe-perm in lifecycle false
6096 verbose lifecycle pngquant-bin@5.0.1~postinstall: PATH: /usr/local/lib/node-v10.15.1-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/local/lib/node-v10.15.1-linux-x64/lib/node_modules/pngquant-bin/node_modules/.bin:/usr/local/lib/node-v10.15.1-linux-x64/lib/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
6097 verbose lifecycle pngquant-bin@5.0.1~postinstall: CWD: /usr/local/lib/node-v10.15.1-linux-x64/lib/node_modules/pngquant-bin
6098 silly lifecycle pngquant-bin@5.0.1~postinstall: Args: [ '-c', 'node lib/install.js' ]
6099 silly lifecycle pngquant-bin@5.0.1~postinstall: Returned: code: 1  signal: null
6100 info lifecycle pngquant-bin@5.0.1~postinstall: Failed to exec postinstall script
6101 timing action:postinstall Completed in 19998ms
6102 verbose unlock done using /home/alan/.npm/_locks/staging-00fd625ac4182fa4.lock for /usr/local/lib/node-v10.15.1-linux-x64/lib/node_modules/.staging
6103 timing stage:rollbackFailedOptional Completed in 227ms
6104 timing stage:runTopLevelLifecycles Completed in 44318ms
6105 verbose stack Error: pngquant-bin@5.0.1 postinstall: `node lib/install.js`
6105 verbose stack Exit status 1
6105 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node-v10.15.1-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
6105 verbose stack     at EventEmitter.emit (events.js:189:13)
6105 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node-v10.15.1-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
6105 verbose stack     at ChildProcess.emit (events.js:189:13)
6105 verbose stack     at maybeClose (internal/child_process.js:970:16)
6105 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
6106 verbose pkgid pngquant-bin@5.0.1
6107 verbose cwd /home/alan
6108 verbose Linux 4.15.0-20-generic
6109 verbose argv "/usr/local/lib/node-v10.15.1-linux-x64/bin/node" "/usr/local/bin/npm" "-g" "install" "pngquant-bin"
6110 verbose node v10.15.1
6111 verbose npm  v6.4.1
6112 error code ELIFECYCLE
6113 error errno 1
6114 error pngquant-bin@5.0.1 postinstall: `node lib/install.js`
6114 error Exit status 1
6115 error Failed at the pngquant-bin@5.0.1 postinstall script.
6115 error This is probably not a problem with npm. There is likely additional logging output above.
6116 verbose exit [ 1, true ]
```

How to resolved ? Thanks

**Comment by kopax** [comment]
Same here:


```
(node:389) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
  ⚠ Response code 503 (Backend unavailable, connection timeout)
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
    at Promise.all.then.arr (/mnt/mesos/sandbox/builds/kopaxgroup-api/link/node_modules/bin-build/node_modules/execa/index.js:231:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pngquant-bin@5.0.1 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pngquant-bin@5.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm timing npm Completed in 122362ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-02-19T20_02_49_736Z-debug.log
ps process exited with code 1
ERROR: Job failed: exit code 1
```

Any idea how we can solve this? All our CIs are down.

**Comment by FSM1** [comment]
also failing with a 503 getting https://raw.github.com/imagemin/pngquant-bin/v5.0.1/vendor/...

Seems like raw.github.com is having issues

**Comment by mdekrey** [comment]
In my case, being on Windows, the error message was confusing. 

As @FSM1 mentions above, this is because the `lib/index.js` references the file from raw.github.com, which appears to be having issues at this time, which isn't really an issue of this library. 

HOWEVER, the fact that this uses a binary without checksum is concerning enough, but the way this URL is determined prevents offline installs (as mentioned in #98), making CI scenarios slower.

**Comment by jblovecrafty** [comment]
I am getting a 400 error on my installs that have been working (last build was on Friday)

`> node lib/install.js
  ‼ Response code 400 (Bad Request)
  ‼ pngquant pre-build test failed
  i compiling from source
  √ pngquant pre-build test passed successfully
  × Error: pngquant failed to build, make sure that libpng-dev is installed
    at Promise.all.then.arr (<path to file>\node_modules\pngquant-bin\node_modules\bin-build\node_modules\execa\index.js:231:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pngquant-bin@4.0.0 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pngquant-bin@4.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

**Comment by Kcharle** [comment]
@jblovecrafty there is a pr to fix this waiting to be merged https://github.com/imagemin/pngquant-bin/pull/99

I would suggest when this is merged you remove your node_modules folder, remove your npm or yarn lock and reinstall your modules.

**Comment by jblovecrafty** [comment]
@Kcharle thank you, any eta on that merge?

**Comment by FSM1** [comment]
and it looks like its sorted in v5.0.2 🍾

**Comment by ChaitanyaKaranam** [comment]
Looks like we still have this issue. Can anyone confirm?

Windows 10
Node: v10.15.1

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pngquant-bin@5.0.2 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pngquant-bin@5.0.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by ChaitanyaKaranam** [comment]
> Looks like we still have this issue. Can anyone confirm?
> 
> Windows 10
> Node: v10.15.1
> 
> ```
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! pngquant-bin@5.0.2 postinstall: `node lib/install.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the pngquant-bin@5.0.2 postinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> ```

Installing Node v11 with python and VS build tools solved this issue for me.

**Comment by lanxxg** [comment]
Follow [this step](https://github.com/nodejs/node-gyp#option-1) On Windows 10 works for me.

**Comment by MWalid** [comment]
It fails on Centos 7

**Comment by carrollbradford** [comment]
We're on WHM + Cpanel and this worked:
 https://www.adminbirds.com/yum/solved-error-pngquant-failed-to-build-make-sure-that-libpng-dev-is-installed/
Not sure if it is the solution to everyone but at least it was for our servers.

**Comment by fullspectrumprocessing** [comment]
im having this problem on MacOs

**Comment by destinytaoer** [comment]
> im having this problem on MacOs when installing modules into a Gatsby project.

you can find `node_modules/pngquant-bin/lib/index.js`, replace `https://raw.githubusercontent.com` with `https://raw.github.com`.Then run `node node_modules/pngquant-bin/lib/index.js`.

**Comment by neoacevedo** [comment]
I'm sorry, but if it is for first install, the `node_modules/pngquant-bin` directory won't be  found because this error.

**Comment by KrisOP** [comment]
> Siga [este paso](https://github.com/nodejs/node-gyp#option-1) En Windows 10 me funciona.

Exacto. Gracias.

**Comment by shahab-k** [comment]
Check this, It works for me thanks..
Ubuntu 18.04
Node v10.15.3
npm 6.4.

**Comment by shahab-k** [comment]
Ubuntu 16.04
pngquant-bin@4.0.0
node.js version v9.9.0
npm version 5.6.0

make 4.1-6 installed

**Comment by BBenQi** [comment]
> Follow [this step](https://github.com/nodejs/node-gyp#option-1) On Windows 10 works for me.

its work fine, thanks

**Comment by arhoy** [comment]
@lanxxg  I am still having the problem I tried to install that library
Please help

**Comment by lanxxg** [comment]
@arhoy Verify that your version of Node [Support & Help](https://github.com/felixrieseberg/windows-build-tools#support--help)

**Comment by cmolinero-meli** [comment]
I'm on Mac and I should use `nvm use` to resolve this. `nvm` is the Node Version Manager. Maybe someone could has the same problem.

**Comment by Rakhee06** [comment]
I had the same issue. Rebuilding Xcode solved the problem. Steps to rebuild Xcode:

xcode-select --print-path (prints the path where Xcode is installed)
sudo rm -r -f [path] (this deleted the Xcode)
xcode-select --install (installs Xcode)

**Comment by trieu-le-eda** [comment]
I got exactly with @alanwei43 's case.
I was using the imagemin for my AWS lambda. It worked well in my local machine (macOS) But when deploy in the lambda it didn't work. I have read a lot of issues reports and also set up a ubuntu machine to deploy my lambda and finally, I got an issue same here. I used Nodejs v12

**Comment by thavaganesh** [comment]
try these steps : 

sudo apt-get install libpng-dev
npm install -g pngquant-bin

solved this issue for me.

**Comment by crew-guy** [comment]
instead I'll suggest, go try imagemin-optipng on npmjs.
Trust me, I was stuck for quite a while here and eventually switching packages is the right option

https://www.npmjs.com/package/imagemin-optipng

**Comment by 1000ch** [comment]
Please try installing this package after making sure that related dependencies are installed, like `libpng` for previous versions and `libimagequant` for the newest version of pngquant.
